name: Validate
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
permissions:
  issues: write
jobs:
  build:
    name: Build action
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Package
        run: npm run package

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected $(git diff --ignore-space-at-eol dist/ | wc -l) uncommitted changes after build."
            exit 1
          fi
        id: diff

  test:
    name: Functional tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tag issue
        uses: ./
        with:
          issue-number: 4
          add-labels: test, bug

      - name: Untag issue
        uses: ./
        with:
          issue-number: 4
          remove-labels: test

      - name: Tag and untag issue
        uses: ./
        with:
          issue-number: 4
          add-labels: test
          remove-labels: bug

      - name: Tag non existing issue (forced error)
        uses: ./
        continue-on-error: true
        with:
          issue-number: 0
          remove-labels: test